### ISSUE TITLE
Failed to configure on ubuntu 12.04

### ISSUE THREAD

**Issue by masonzhang** [msorvig/qt5-qtbase-nacl#1]
Hi,

I followed your guideline http://qt-project.org/wiki/Qt_for_Google_Native_Client to sync code from qt5 first, then replace qtbase/qttools with your repository. But when configure, it fails. Is there any clue for me to resolve the error message below? (I tried to compile Qt5, and it works, but when I created a new folder to sync and build qt5-nacl, it fails)
# 

test@test-VirtualBox:~/qt5$ ./configure -xplatform unsupported/nacl-g++ -device-option CROSS_COMPILE=~/nacl_sdk/pepper_23/toolchain/linux_x86_glibc/bin/ -nomake examples -nomake tests -developer-build -opensource -confirm-license -reduce-relocations
- /home/test/qt5/qtbase/configure -xplatform unsupported/nacl-g++ -device-option CROSS_COMPILE=/home/test/nacl_sdk/pepper_23/toolchain/linux_x86_glibc/bin/ -nomake examples -nomake tests -developer-build -opensource -confirm-license -reduce-relocations

This is the Qt Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.

You have already accepted the terms of the  license.

<srcbase> = /home/test/qt5/qtbase 
<outbase> = /home/test/qt5/qtbase 
Creating qmake. Please wait...
make: Nothing to be done for `first'.
Warning: Disabling pkg-config since PKG_CONFIG_LIBDIR is not set.
Warning: Disabling pkg-config since PKG_CONFIG_SYSROOT_DIR is not set.
on nacl
WARNING: Unable to find file .device.vars
No QPA platform plugin enabled!
 If you really want to build without a QPA platform plugin you must pass
 -no-qpa-platform-guard to configure. Doing this will
 produce a Qt that can not run GUI applications.
 The dependencies needed for xcb to build are listed in
 src/plugins/platforms/xcb/README
qtbase/configure exited with non-zero status.
# .

I tried to add -no-pkg-config to configure command line, it still fails.

Thanks a lot!

**Comment by msorvig** [comment]
I'm sorry! The wiki contained outdated information. 

I've cleared that out now and added a pointer to the [nacl-readme](https://github.com/msorvig/qt5-qtbase-nacl/blob/nacl-5.4/nacl-readme) file, which contains up to date info.
