### ISSUE TITLE
Failed to make module-qtdeclarative

### ISSUE THREAD

**Issue by theshadowx** [msorvig/qt5-qtbase-nacl#2]
OS : Ubuntu 14.04 LTS 64bit
Qt : 5.4.2 (git)
NaCl : pepper 41
Using linux_x86_newlib as compiler, the compilation of qtbase succeeds whithout any problem. 
But when I do:

```
 > $ make module-qtdeclarative 
```

I receive this error:

```
Qt5.4.2/qtdeclarative/src/qml/jsruntime/qv4engine.cpp: In function ‘quintptr getStackLimit()’:
Qt5.4.2/qtdeclarative/src/qml/jsruntime/qv4engine.cpp:118: error: ‘pthread_getattr_np’ was not declared in this scope
Qt5.4.2/qtdeclarative/src/qml/jsruntime/qv4engine.cpp:121: error: ‘pthread_attr_getstack’ was not declared in this scope
```

I have installed pthread-dev with this:

```
>$ sudo apt-get install libpthread-stubs0-dev libpthread-workqueue-dev 
```

Please could you help me to solve this problem.

Thanks

**Comment by daiweili** [comment]
You'll need https://github.com/msorvig/qt5-qtdeclarative-nacl as well, which has some tweaks in order to compile/work with NaCl.

**Comment by theshadowx** [comment]
I tried to replace the qtdeclarative contained in the Qt5.4.2 with the one you mentioned.
I execute the script contained in bin folder so that it modifies the path to the includes in the files.

The problem is that when I do :

```
>$ make module-qtdeclarative 
```

I get errors that some includes don't exist, so I open the files to check and I see that the path to these includes is not correct. That means that the script didn't work well. 

so I didn't continue in this path.

**Comment by theshadowx** [comment]
@daiweili, you were right, I have asked a friend of mine to execute the script that exists in the bin folder of https://github.com/msorvig/qt5-qtdeclarative-nacl as it worked for him, and I used the resulted folder, and finally it worked. :)

Thanks
