### ISSUE TITLE
[Question] Linking between outside resources and NaCl Qml app

### ISSUE THREAD

**Issue by theshadowx** [msorvig/qt5-qtbase-nacl#6]
I have my qml app successfully compiled (NaCl) and launched in the browser, I would like to know how to load/link resources (picture / videos) to the app. 

I can't use qrc as the files I want to use are big.

**Comment by msorvig** [comment]
Hi!

http network access back to the host (following the same origin policy) using QNetworkAccessManager on the Gui thread currently works. This unfortunately breaks QML which uses a background thread for network access. I'd say making this work is pretty high on the TODO list.

**Comment by msorvig** [comment]
I've pushed an update now which should improve things regarding networking. See test/example at tests/manual/nacl/window_controls_network/main.qml .

**Comment by theshadowx** [comment]
Thanks a lot, 
I'll take a look.
