### ISSUE TITLE
[QUESTION] Which branch shall I use ?

### ISSUE THREAD

**Issue by theshadowx** [msorvig/qt5-qtbase-nacl#7]
Hi, 
I've just seen that there is a new branch called nacl-dev, but the default one is still nacl-5.4.

So, which branch shall I use?

Thanks

**Comment by msorvig** [comment]
Hi, in short:

nacl-5.4 is a stable branch which won't receive further updates, except perhaps for the occasional bugfix and merging 5.4.x content.

nacl-dev is a development branch which tracks qtbase/wip/nacl which again tracks the qtbase/dev (All from codereview.qt-project.org). This one will be more frequently updated.

At this point they are pretty much equal, except that nacl-dev has a newer (unreleased) Qt version. If you want stability, use nacl-5.4, if you want to participate in development use nacl-dev.

**Comment by theshadowx** [comment]
thanks
